// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: companion_regs_pkg
// =============================================================================
package companion_regs_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic  overflow; // RW bits bit 0
    logic  underflow; // RW bits bit 1
  } status_fields_t;
  typedef struct packed {
    logic  overflow; // RW bits bit 0
  } root_intr_enable_fields_t;
  typedef struct packed {
    logic  underflow; // RW bits bit 0
  } err_intr_enable_fields_t;
  typedef struct packed {
    logic  overflow; // RW bits bit 0
  } root_intr_mask_fields_t;
  typedef struct packed {
    logic  underflow; // RW bits bit 0
  } err_intr_mask_fields_t;
  typedef struct packed {
    logic [4:0] level; // RO bits 4:0
    logic  full; // RO bits bit 5
    logic  empty; // RO bits bit 6
    logic  almost_full; // RO bits bit 7
  } data_fifo_status_fields_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_STATUS_ADDR = 'h0;
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_ROOT_INTR_ENABLE_ADDR = 'h40;
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_ERR_INTR_ENABLE_ADDR = 'h44;
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_ROOT_INTR_MASK_ADDR = 'h60;
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_ERR_INTR_MASK_ADDR = 'h64;
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_DATA_FIFO_STATUS_ADDR = 'h20;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] COMPANION_REGS_DATA_FIFO_ADDR = 'h10;

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [31:0] status;
    logic [31:0] root_intr_enable;
    logic [31:0] err_intr_enable;
    logic [31:0] root_intr_mask;
    logic [31:0] err_intr_mask;
    logic [31:0] data_fifo_status;
    // buffer `data_fifo` — FIFO depth=16 (bus pushes, bus pops)
    logic                                          buf_data_fifo_push;
    logic [CPUIF_DATA_W-1:0]                       buf_data_fifo_wdata;
    logic                                          buf_data_fifo_pop;
  } companion_regs__out_t;


  // ---- Top-level hwif (HW write port) ---------------------------------------
  // Per HW-writable field: `<reg>_<field>` carries the candidate value;
  // `<reg>_<field>_we` is a single-cycle strobe that latches it into storage.
  // HW writes take precedence over SW writes on the same cycle.
  typedef struct packed {
    logic                                          status_overflow_intr;
    logic                                          status_underflow_intr;
    logic                                          data_fifo_status_level_we;
    logic [4:0] data_fifo_status_level;
    logic                                          data_fifo_status_full_we;
    logic  data_fifo_status_full;
    logic                                          data_fifo_status_empty_we;
    logic  data_fifo_status_empty;
    logic                                          data_fifo_status_almost_full_we;
    logic  data_fifo_status_almost_full;
    // buffer `data_fifo` — FIFO read data
    logic [CPUIF_DATA_W-1:0]                       buf_data_fifo_rdata;
  } companion_regs__in_t;

endpackage : companion_regs_pkg

// =============================================================================
// Module: companion_regs_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module companion_regs_regs
  import companion_regs_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output companion_regs__out_t hwif_out,

  // ---- HW write port --------------------------------------------------------
  input  companion_regs__in_t hwif_in,

  // ---- IRQ outputs ----------------------------------------------------------
  output logic                          irq,
  output logic                          irq_err
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [31:0] RD_MASK_STATUS = 32'h3;
  localparam logic [31:0] RD_MASK_ROOT_INTR_ENABLE = 32'h1;
  localparam logic [31:0] RD_MASK_ERR_INTR_ENABLE = 32'h1;
  localparam logic [31:0] RD_MASK_ROOT_INTR_MASK = 32'h1;
  localparam logic [31:0] RD_MASK_ERR_INTR_MASK = 32'h1;
  localparam logic [31:0] RD_MASK_DATA_FIFO_STATUS = 32'hff;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [31:0] storage_status;
  logic [31:0] storage_root_intr_enable;
  logic [31:0] storage_err_intr_enable;
  logic [31:0] storage_root_intr_mask;
  logic [31:0] storage_err_intr_mask;
  logic [31:0] storage_data_fifo_status;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_status;
  logic rd_hit_status;
  assign wr_hit_status = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_STATUS_ADDR);
  assign rd_hit_status = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_STATUS_ADDR);
  logic wr_hit_root_intr_enable;
  logic rd_hit_root_intr_enable;
  assign wr_hit_root_intr_enable = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ROOT_INTR_ENABLE_ADDR);
  assign rd_hit_root_intr_enable = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ROOT_INTR_ENABLE_ADDR);
  logic wr_hit_err_intr_enable;
  logic rd_hit_err_intr_enable;
  assign wr_hit_err_intr_enable = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ERR_INTR_ENABLE_ADDR);
  assign rd_hit_err_intr_enable = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ERR_INTR_ENABLE_ADDR);
  logic wr_hit_root_intr_mask;
  logic rd_hit_root_intr_mask;
  assign wr_hit_root_intr_mask = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ROOT_INTR_MASK_ADDR);
  assign rd_hit_root_intr_mask = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ROOT_INTR_MASK_ADDR);
  logic wr_hit_err_intr_mask;
  logic rd_hit_err_intr_mask;
  assign wr_hit_err_intr_mask = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ERR_INTR_MASK_ADDR);
  assign rd_hit_err_intr_mask = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_ERR_INTR_MASK_ADDR);
  logic wr_hit_data_fifo_status;
  logic rd_hit_data_fifo_status;
  assign wr_hit_data_fifo_status = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_DATA_FIFO_STATUS_ADDR);
  assign rd_hit_data_fifo_status = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_DATA_FIFO_STATUS_ADDR);
  logic wr_hit_buf_data_fifo;
  logic rd_hit_buf_data_fifo;
  assign wr_hit_buf_data_fifo = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_DATA_FIFO_ADDR);
  assign rd_hit_buf_data_fifo = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == COMPANION_REGS_DATA_FIFO_ADDR);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_status[0] <= '0;
    end else if (intr_event_status_overflow) begin
      storage_status[0] <= '1;
    end else if (wr_hit_status) begin
      storage_status[0] <= storage_status[0] & ~(cpuif_wr_data[0] & cpuif_wr_biten[0]);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_status[1] <= '0;
    end else if (intr_event_status_underflow) begin
      storage_status[1] <= '1;
    end else if (wr_hit_status) begin
      storage_status[1] <= storage_status[1] & ~(cpuif_wr_data[1] & cpuif_wr_biten[1]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_root_intr_enable[0] <= '0;
    end else if (wr_hit_root_intr_enable) begin
      storage_root_intr_enable[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_root_intr_enable[0] & ~cpuif_wr_biten[0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_err_intr_enable[0] <= '0;
    end else if (wr_hit_err_intr_enable) begin
      storage_err_intr_enable[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_err_intr_enable[0] & ~cpuif_wr_biten[0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_root_intr_mask[0] <= '0;
    end else if (wr_hit_root_intr_mask) begin
      storage_root_intr_mask[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_root_intr_mask[0] & ~cpuif_wr_biten[0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_err_intr_mask[0] <= '0;
    end else if (wr_hit_err_intr_mask) begin
      storage_err_intr_mask[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_err_intr_mask[0] & ~cpuif_wr_biten[0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_data_fifo_status[4:0] <= '0;
    end else if (hwif_in.data_fifo_status_level_we) begin
      storage_data_fifo_status[4:0] <= hwif_in.data_fifo_status_level;
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_data_fifo_status[5] <= '0;
    end else if (hwif_in.data_fifo_status_full_we) begin
      storage_data_fifo_status[5] <= hwif_in.data_fifo_status_full;
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_data_fifo_status[6] <= '0;
    end else if (hwif_in.data_fifo_status_empty_we) begin
      storage_data_fifo_status[6] <= hwif_in.data_fifo_status_empty;
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_data_fifo_status[7] <= '0;
    end else if (hwif_in.data_fifo_status_almost_full_we) begin
      storage_data_fifo_status[7] <= hwif_in.data_fifo_status_almost_full;
    end
  end



  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_status | rd_hit_status |
      wr_hit_root_intr_enable | rd_hit_root_intr_enable |
      wr_hit_err_intr_enable | rd_hit_err_intr_enable |
      wr_hit_root_intr_mask | rd_hit_root_intr_mask |
      wr_hit_err_intr_mask | rd_hit_err_intr_mask |
      wr_hit_data_fifo_status | rd_hit_data_fifo_status |
      wr_hit_buf_data_fifo |
      rd_hit_buf_data_fifo |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_status: cpuif_rd_data_next = CPUIF_DATA_W'(storage_status & RD_MASK_STATUS);
      rd_hit_root_intr_enable: cpuif_rd_data_next = CPUIF_DATA_W'(storage_root_intr_enable & RD_MASK_ROOT_INTR_ENABLE);
      rd_hit_err_intr_enable: cpuif_rd_data_next = CPUIF_DATA_W'(storage_err_intr_enable & RD_MASK_ERR_INTR_ENABLE);
      rd_hit_root_intr_mask: cpuif_rd_data_next = CPUIF_DATA_W'(storage_root_intr_mask & RD_MASK_ROOT_INTR_MASK);
      rd_hit_err_intr_mask: cpuif_rd_data_next = CPUIF_DATA_W'(storage_err_intr_mask & RD_MASK_ERR_INTR_MASK);
      rd_hit_data_fifo_status: cpuif_rd_data_next = CPUIF_DATA_W'(storage_data_fifo_status & RD_MASK_DATA_FIFO_STATUS);
      rd_hit_buf_data_fifo: cpuif_rd_data_next = hwif_in.buf_data_fifo_rdata;
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.status = storage_status;
  assign hwif_out.root_intr_enable = storage_root_intr_enable;
  assign hwif_out.err_intr_enable = storage_err_intr_enable;
  assign hwif_out.root_intr_mask = storage_root_intr_mask;
  assign hwif_out.err_intr_mask = storage_err_intr_mask;
  assign hwif_out.data_fifo_status = storage_data_fifo_status;

  // ---------------------------------------------------------------------------
  // Interrupt edge-detect prev registers + event signals
  // ---------------------------------------------------------------------------
  wire intr_event_status_overflow = hwif_in.status_overflow_intr;
  logic intr_prev_status_underflow;
  always_ff @(posedge clk) begin
    if (!rst_n) intr_prev_status_underflow <= 1'b0;
    else        intr_prev_status_underflow <= hwif_in.status_underflow_intr;
  end
  wire intr_event_status_underflow = ~intr_prev_status_underflow & hwif_in.status_underflow_intr;

  // ---------------------------------------------------------------------------
  // IRQ OR-reduce outputs
  // ---------------------------------------------------------------------------
  assign irq = ((storage_status[0] & storage_root_intr_enable[0]) & ~storage_root_intr_mask[0]);
  assign irq_err = ((storage_status[1] & storage_err_intr_enable[0]) & ~storage_err_intr_mask[0]);

  // ---------------------------------------------------------------------------
  // Buffer FIFO handshake (M6b)
  // Bus writes pulse `hwif_out.buf_<n>_push` for one cycle (combinational
  // with `wr_hit_buf_<n>`) and drive `hwif_out.buf_<n>_wdata` to
  // `cpuif_wr_data`. Bus reads pulse `hwif_out.buf_<n>_pop` and return
  // `hwif_in.buf_<n>_rdata`. The regblock intentionally does NOT
  // instantiate FIFO storage — user RTL plugs its own FIFO into the
  // hwif handshake. Status/level/full/empty exposure to SW is left to
  // the user (declare a separate RO register wired to `hwif_in`).
  // ---------------------------------------------------------------------------
  assign hwif_out.buf_data_fifo_push  = wr_hit_buf_data_fifo;
  assign hwif_out.buf_data_fifo_wdata = cpuif_wr_data;
  assign hwif_out.buf_data_fifo_pop   = rd_hit_buf_data_fifo;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : companion_regs_regs

// =============================================================================
// APB3 → native CPUIF wrapper.
//
// Handshake: psel + penable starts a transaction. We assert pready as soon as
// the regs module's cpuif_*_ack returns (single-cycle for now). pslverr is
// driven by the regs module's wr_err / rd_err.
//
// Note: APB3 has no per-byte write strobe. wdata is fanned out to every bit
// of cpuif_wr_biten — every-bit-enabled writes match APB's "the whole word
// is what got written" semantics.
// =============================================================================
module companion_regs_apb3
  import companion_regs_pkg::*;
(
  input  logic                          pclk,
  input  logic                          presetn,

  input  logic                          psel,
  input  logic                          penable,
  input  logic                          pwrite,
  input  logic [CPUIF_ADDR_W-1:0]       paddr,
  input  logic [CPUIF_DATA_W-1:0]       pwdata,

  output logic [CPUIF_DATA_W-1:0]       prdata,
  output logic                          pready,
  output logic                          pslverr,

  output companion_regs__out_t          hwif_out,
  input  companion_regs__in_t           hwif_in,
  output logic                          irq,
  output logic                          irq_err
);

  // ---------------------------------------------------------------------------
  // Native CPUIF wires
  // ---------------------------------------------------------------------------
  logic                          cpuif_req;
  logic                          cpuif_req_is_wr;
  logic [CPUIF_ADDR_W-1:0]       cpuif_addr;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten;
  logic                          cpuif_rd_ack;
  logic                          cpuif_rd_err;
  logic [CPUIF_DATA_W-1:0]       cpuif_rd_data;
  logic                          cpuif_wr_ack;
  logic                          cpuif_wr_err;

  // ---------------------------------------------------------------------------
  // APB → CPUIF translation. Request goes out on the ACCESS phase (psel+penable);
  // ready latches in the cycle after, and the next access starts after pready
  // is sampled, so we don't need a per-request FIFO.
  // ---------------------------------------------------------------------------
  assign cpuif_req       = psel & penable & ~pready;
  assign cpuif_req_is_wr = pwrite;
  assign cpuif_addr      = paddr;
  assign cpuif_wr_data   = pwdata;
  assign cpuif_wr_biten  = {CPUIF_DATA_W{1'b1}}; // APB3 has no per-byte strobe

  // ---------------------------------------------------------------------------
  // CPUIF → APB. Ack from either direction satisfies pready; err from either
  // direction satisfies pslverr.
  // ---------------------------------------------------------------------------
  assign pready  = cpuif_rd_ack | cpuif_wr_ack;
  assign pslverr = cpuif_rd_err | cpuif_wr_err;
  assign prdata  = cpuif_rd_data;

  // ---------------------------------------------------------------------------
  // Inner regs module
  // ---------------------------------------------------------------------------
  companion_regs_regs u_regs (
    .clk            (pclk),
    .rst_n          (presetn),
    .cpuif_req      (cpuif_req),
    .cpuif_req_is_wr(cpuif_req_is_wr),
    .cpuif_addr     (cpuif_addr),
    .cpuif_wr_data  (cpuif_wr_data),
    .cpuif_wr_biten (cpuif_wr_biten),
    .cpuif_rd_ack   (cpuif_rd_ack),
    .cpuif_rd_err   (cpuif_rd_err),
    .cpuif_rd_data  (cpuif_rd_data),
    .cpuif_wr_ack   (cpuif_wr_ack),
    .cpuif_wr_err   (cpuif_wr_err),
    .hwif_out       (hwif_out),
    .hwif_in        (hwif_in),
    .irq            (irq),
    .irq_err (irq_err)
  );

endmodule : companion_regs_apb3

// =============================================================================
// UVM RAL package: companion_regs_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _COMPANION_REGS_RAL_PKG_SV
`define _COMPANION_REGS_RAL_PKG_SV

package companion_regs_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `status` --------------------------------------
  class companion_regs_status_reg extends uvm_reg;

    rand uvm_reg_field overflow;

    rand uvm_reg_field underflow;


    function new(string name = "companion_regs_status_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.overflow = uvm_reg_field::type_id::create("overflow");
      this.overflow.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("W1C"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.underflow = uvm_reg_field::type_id::create("underflow");
      this.underflow.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (1),
        .access                  ("W1C"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : companion_regs_status_reg


  // ---- register `root_intr_enable` --------------------------------------
  class companion_regs_root_intr_enable_reg extends uvm_reg;

    rand uvm_reg_field overflow;


    function new(string name = "companion_regs_root_intr_enable_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.overflow = uvm_reg_field::type_id::create("overflow");
      this.overflow.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : companion_regs_root_intr_enable_reg


  // ---- register `err_intr_enable` --------------------------------------
  class companion_regs_err_intr_enable_reg extends uvm_reg;

    rand uvm_reg_field underflow;


    function new(string name = "companion_regs_err_intr_enable_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.underflow = uvm_reg_field::type_id::create("underflow");
      this.underflow.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : companion_regs_err_intr_enable_reg


  // ---- register `root_intr_mask` --------------------------------------
  class companion_regs_root_intr_mask_reg extends uvm_reg;

    rand uvm_reg_field overflow;


    function new(string name = "companion_regs_root_intr_mask_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.overflow = uvm_reg_field::type_id::create("overflow");
      this.overflow.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : companion_regs_root_intr_mask_reg


  // ---- register `err_intr_mask` --------------------------------------
  class companion_regs_err_intr_mask_reg extends uvm_reg;

    rand uvm_reg_field underflow;


    function new(string name = "companion_regs_err_intr_mask_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.underflow = uvm_reg_field::type_id::create("underflow");
      this.underflow.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : companion_regs_err_intr_mask_reg


  // ---- register `data_fifo_status` --------------------------------------
  class companion_regs_data_fifo_status_reg extends uvm_reg;

    rand uvm_reg_field level;

    rand uvm_reg_field full;

    rand uvm_reg_field empty;

    rand uvm_reg_field almost_full;


    function new(string name = "companion_regs_data_fifo_status_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.level = uvm_reg_field::type_id::create("level");
      this.level.configure(
        .parent                  (this),
        .size                    (5),
        .lsb_pos                 (0),
        .access                  ("RO"),
        .volatile                (1'b1),
        .reset                   (5'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.full = uvm_reg_field::type_id::create("full");
      this.full.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (5),
        .access                  ("RO"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.empty = uvm_reg_field::type_id::create("empty");
      this.empty.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (6),
        .access                  ("RO"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.almost_full = uvm_reg_field::type_id::create("almost_full");
      this.almost_full.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (7),
        .access                  ("RO"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : companion_regs_data_fifo_status_reg



  // ---- register block -------------------------------------------------------
  class companion_regs_reg_block extends uvm_reg_block;

    rand companion_regs_status_reg status;

    rand companion_regs_root_intr_enable_reg root_intr_enable;

    rand companion_regs_err_intr_enable_reg err_intr_enable;

    rand companion_regs_root_intr_mask_reg root_intr_mask;

    rand companion_regs_err_intr_mask_reg err_intr_mask;

    rand companion_regs_data_fifo_status_reg data_fifo_status;


    function new(string name = "companion_regs_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.status = companion_regs_status_reg::type_id::create("status");
      this.status.configure(this, null, "");
      this.status.build();
      this.default_map.add_reg(this.status, 8'h0, "RW");



      this.root_intr_enable = companion_regs_root_intr_enable_reg::type_id::create("root_intr_enable");
      this.root_intr_enable.configure(this, null, "");
      this.root_intr_enable.build();
      this.default_map.add_reg(this.root_intr_enable, 8'h40, "RW");



      this.err_intr_enable = companion_regs_err_intr_enable_reg::type_id::create("err_intr_enable");
      this.err_intr_enable.configure(this, null, "");
      this.err_intr_enable.build();
      this.default_map.add_reg(this.err_intr_enable, 8'h44, "RW");



      this.root_intr_mask = companion_regs_root_intr_mask_reg::type_id::create("root_intr_mask");
      this.root_intr_mask.configure(this, null, "");
      this.root_intr_mask.build();
      this.default_map.add_reg(this.root_intr_mask, 8'h60, "RW");



      this.err_intr_mask = companion_regs_err_intr_mask_reg::type_id::create("err_intr_mask");
      this.err_intr_mask.configure(this, null, "");
      this.err_intr_mask.build();
      this.default_map.add_reg(this.err_intr_mask, 8'h64, "RW");



      this.data_fifo_status = companion_regs_data_fifo_status_reg::type_id::create("data_fifo_status");
      this.data_fifo_status.configure(this, null, "");
      this.data_fifo_status.build();
      this.default_map.add_reg(this.data_fifo_status, 8'h20, "RO");



      lock_model();
    endfunction

  endclass : companion_regs_reg_block

endpackage : companion_regs_ral_pkg

`endif // _COMPANION_REGS_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `companion_regs_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `companion_regs_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _COMPANION_REGS_RAL_SMOKE_SEQ_SV
`define _COMPANION_REGS_RAL_SMOKE_SEQ_SV

package companion_regs_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import companion_regs_ral_pkg::*;

  class companion_regs_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(companion_regs_ral_smoke_seq)

    companion_regs_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "companion_regs_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // status — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.status.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(status) status=%s", status.name()))
      end
      model.status.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(status) status=%s", status.name()))
      end



      // root_intr_enable — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.root_intr_enable.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(root_intr_enable) status=%s", status.name()))
      end
      model.root_intr_enable.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(root_intr_enable) status=%s", status.name()))
      end



      // err_intr_enable — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.err_intr_enable.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(err_intr_enable) status=%s", status.name()))
      end
      model.err_intr_enable.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(err_intr_enable) status=%s", status.name()))
      end



      // root_intr_mask — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.root_intr_mask.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(root_intr_mask) status=%s", status.name()))
      end
      model.root_intr_mask.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(root_intr_mask) status=%s", status.name()))
      end



      // err_intr_mask — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.err_intr_mask.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(err_intr_mask) status=%s", status.name()))
      end
      model.err_intr_mask.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(err_intr_mask) status=%s", status.name()))
      end



      // data_fifo_status — RO: read-only smoke (no write).
      model.data_fifo_status.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(data_fifo_status) status=%s", status.name()))
      end


    endtask

  endclass : companion_regs_ral_smoke_seq

endpackage : companion_regs_ral_smoke_pkg

`endif // _COMPANION_REGS_RAL_SMOKE_SEQ_SV

