// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: reserved_external_pkg
// =============================================================================
package reserved_external_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic [31:0] cmd; // RW bits 31:0
  } ext_ctrl_fields_t;
  typedef struct packed {
    logic [7:0] tag; // RW bits 7:0
  } scratch_fields_t;
  typedef struct packed {
    logic  enable; // RW bits bit 0
  } ctrl_preserve_fields_t;
  typedef struct packed {
    logic  enable; // RW bits bit 0
  } ctrl_zero_fields_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] RESERVED_EXTERNAL_CTRL_ZERO_ADDR = 'h0;
  localparam logic [CPUIF_ADDR_W-1:0] RESERVED_EXTERNAL_CTRL_PRESERVE_ADDR = 'h4;
  localparam logic [CPUIF_ADDR_W-1:0] RESERVED_EXTERNAL_SCRATCH_ADDR = 'h8;
  localparam logic [CPUIF_ADDR_W-1:0] RESERVED_EXTERNAL_EXT_CTRL_ADDR = 'hc;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [31:0] ctrl_zero;
    logic [31:0] ctrl_preserve;
    logic [31:0] scratch;
    // external `ext_ctrl` — bus → user RTL
    logic                                          ext_ctrl_ext_wr_hit;
    logic                                          ext_ctrl_ext_rd_hit;
    logic [31:0] ext_ctrl_ext_wr_data;
  } reserved_external__out_t;


  // ---- Top-level hwif (HW write port) ---------------------------------------
  // Per HW-writable field: `<reg>_<field>` carries the candidate value;
  // `<reg>_<field>_we` is a single-cycle strobe that latches it into storage.
  // HW writes take precedence over SW writes on the same cycle.
  typedef struct packed {
    // external `ext_ctrl` — user RTL → bus
    logic [31:0] ext_ctrl_ext_rd_data;
  } reserved_external__in_t;

endpackage : reserved_external_pkg

// =============================================================================
// Module: reserved_external_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module reserved_external_regs
  import reserved_external_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output reserved_external__out_t hwif_out,

  // ---- HW write port --------------------------------------------------------
  input  reserved_external__in_t hwif_in
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [31:0] RD_MASK_CTRL_ZERO = 32'h1;
  localparam logic [31:0] RD_MASK_CTRL_PRESERVE = 32'hffffffff;
  localparam logic [31:0] RD_MASK_SCRATCH = 32'hffffffff;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [31:0] storage_ctrl_zero;
  logic [31:0] storage_ctrl_preserve;
  logic [31:0] storage_scratch;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_ctrl_zero;
  logic rd_hit_ctrl_zero;
  assign wr_hit_ctrl_zero = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_CTRL_ZERO_ADDR);
  assign rd_hit_ctrl_zero = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_CTRL_ZERO_ADDR);
  logic wr_hit_ctrl_preserve;
  logic rd_hit_ctrl_preserve;
  assign wr_hit_ctrl_preserve = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_CTRL_PRESERVE_ADDR);
  assign rd_hit_ctrl_preserve = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_CTRL_PRESERVE_ADDR);
  logic wr_hit_scratch;
  logic rd_hit_scratch;
  assign wr_hit_scratch = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_SCRATCH_ADDR);
  assign rd_hit_scratch = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_SCRATCH_ADDR);
  logic wr_hit_ext_ctrl;
  logic rd_hit_ext_ctrl;
  assign wr_hit_ext_ctrl = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_EXT_CTRL_ADDR);
  assign rd_hit_ext_ctrl = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == RESERVED_EXTERNAL_EXT_CTRL_ADDR);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl_zero[0] <= '0;
    end else if (wr_hit_ctrl_zero) begin
      storage_ctrl_zero[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_ctrl_zero[0] & ~cpuif_wr_biten[0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl_preserve[0] <= 1'h1;
    end else if (wr_hit_ctrl_preserve) begin
      storage_ctrl_preserve[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_ctrl_preserve[0] & ~cpuif_wr_biten[0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_scratch[7:0] <= 8'h0;
    end else if (wr_hit_scratch) begin
      storage_scratch[7:0] <= (cpuif_wr_data[7:0] & cpuif_wr_biten[7:0]) | (storage_scratch[7:0] & ~cpuif_wr_biten[7:0]);
    end
  end

  // reserved bits (rw_storage policy)
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_scratch[31:8] <= 24'h0;
    end else if (wr_hit_scratch) begin
      storage_scratch[31:8] <= (cpuif_wr_data[31:8] & cpuif_wr_biten[31:8]) | (storage_scratch[31:8] & ~cpuif_wr_biten[31:8]);
    end
  end


  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_ctrl_zero | rd_hit_ctrl_zero |
      wr_hit_ctrl_preserve | rd_hit_ctrl_preserve |
      wr_hit_scratch | rd_hit_scratch |
      wr_hit_ext_ctrl | rd_hit_ext_ctrl |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_ctrl_zero: cpuif_rd_data_next = CPUIF_DATA_W'(storage_ctrl_zero & RD_MASK_CTRL_ZERO);
      rd_hit_ctrl_preserve: cpuif_rd_data_next = CPUIF_DATA_W'(storage_ctrl_preserve & RD_MASK_CTRL_PRESERVE);
      rd_hit_scratch: cpuif_rd_data_next = CPUIF_DATA_W'(storage_scratch & RD_MASK_SCRATCH);
      rd_hit_ext_ctrl: cpuif_rd_data_next = CPUIF_DATA_W'(hwif_in.ext_ctrl_ext_rd_data);
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.ctrl_zero = storage_ctrl_zero;
  assign hwif_out.ctrl_preserve = storage_ctrl_preserve;
  assign hwif_out.scratch = storage_scratch;
  assign hwif_out.ext_ctrl_ext_wr_hit  = wr_hit_ext_ctrl;
  assign hwif_out.ext_ctrl_ext_rd_hit  = rd_hit_ext_ctrl;
  assign hwif_out.ext_ctrl_ext_wr_data = cpuif_wr_data;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : reserved_external_regs

// =============================================================================
// UVM RAL package: reserved_external_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _RESERVED_EXTERNAL_RAL_PKG_SV
`define _RESERVED_EXTERNAL_RAL_PKG_SV

package reserved_external_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `ctrl_zero` --------------------------------------
  class reserved_external_ctrl_zero_reg extends uvm_reg;

    rand uvm_reg_field enable;


    function new(string name = "reserved_external_ctrl_zero_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.enable = uvm_reg_field::type_id::create("enable");
      this.enable.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : reserved_external_ctrl_zero_reg


  // ---- register `ctrl_preserve` --------------------------------------
  class reserved_external_ctrl_preserve_reg extends uvm_reg;

    rand uvm_reg_field enable;


    function new(string name = "reserved_external_ctrl_preserve_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.enable = uvm_reg_field::type_id::create("enable");
      this.enable.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h1),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : reserved_external_ctrl_preserve_reg


  // ---- register `scratch` --------------------------------------
  class reserved_external_scratch_reg extends uvm_reg;

    rand uvm_reg_field tag;


    function new(string name = "reserved_external_scratch_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.tag = uvm_reg_field::type_id::create("tag");
      this.tag.configure(
        .parent                  (this),
        .size                    (8),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (8'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : reserved_external_scratch_reg


  // ---- register `ext_ctrl` --------------------------------------
  class reserved_external_ext_ctrl_reg extends uvm_reg;

    rand uvm_reg_field cmd;


    function new(string name = "reserved_external_ext_ctrl_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.cmd = uvm_reg_field::type_id::create("cmd");
      this.cmd.configure(
        .parent                  (this),
        .size                    (32),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (32'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : reserved_external_ext_ctrl_reg



  // ---- register block -------------------------------------------------------
  class reserved_external_reg_block extends uvm_reg_block;

    rand reserved_external_ctrl_zero_reg ctrl_zero;

    rand reserved_external_ctrl_preserve_reg ctrl_preserve;

    rand reserved_external_scratch_reg scratch;

    rand reserved_external_ext_ctrl_reg ext_ctrl;


    function new(string name = "reserved_external_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.ctrl_zero = reserved_external_ctrl_zero_reg::type_id::create("ctrl_zero");
      this.ctrl_zero.configure(this, null, "");
      this.ctrl_zero.build();
      this.default_map.add_reg(this.ctrl_zero, 8'h0, "RW");



      this.ctrl_preserve = reserved_external_ctrl_preserve_reg::type_id::create("ctrl_preserve");
      this.ctrl_preserve.configure(this, null, "");
      this.ctrl_preserve.build();
      this.default_map.add_reg(this.ctrl_preserve, 8'h4, "RW");



      this.scratch = reserved_external_scratch_reg::type_id::create("scratch");
      this.scratch.configure(this, null, "");
      this.scratch.build();
      this.default_map.add_reg(this.scratch, 8'h8, "RW");



      this.ext_ctrl = reserved_external_ext_ctrl_reg::type_id::create("ext_ctrl");
      this.ext_ctrl.configure(this, null, "");
      this.ext_ctrl.build();
      this.default_map.add_reg(this.ext_ctrl, 8'hc, "RW");



      lock_model();
    endfunction

  endclass : reserved_external_reg_block

endpackage : reserved_external_ral_pkg

`endif // _RESERVED_EXTERNAL_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `reserved_external_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `reserved_external_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _RESERVED_EXTERNAL_RAL_SMOKE_SEQ_SV
`define _RESERVED_EXTERNAL_RAL_SMOKE_SEQ_SV

package reserved_external_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import reserved_external_ral_pkg::*;

  class reserved_external_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(reserved_external_ral_smoke_seq)

    reserved_external_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "reserved_external_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // ctrl_zero — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.ctrl_zero.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(ctrl_zero) status=%s", status.name()))
      end
      model.ctrl_zero.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(ctrl_zero) status=%s", status.name()))
      end



      // ctrl_preserve — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.ctrl_preserve.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(ctrl_preserve) status=%s", status.name()))
      end
      model.ctrl_preserve.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(ctrl_preserve) status=%s", status.name()))
      end



      // scratch — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.scratch.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(scratch) status=%s", status.name()))
      end
      model.scratch.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(scratch) status=%s", status.name()))
      end



      // ext_ctrl — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.ext_ctrl.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(ext_ctrl) status=%s", status.name()))
      end
      model.ext_ctrl.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(ext_ctrl) status=%s", status.name()))
      end


    endtask

  endclass : reserved_external_ral_smoke_seq

endpackage : reserved_external_ral_smoke_pkg

`endif // _RESERVED_EXTERNAL_RAL_SMOKE_SEQ_SV

