// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: precedence_override_pkg
// =============================================================================
package precedence_override_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic  hw_wins; // RW bits bit 0
    logic  sw_wins; // RW bits bit 1
  } ctrl_fields_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] PRECEDENCE_OVERRIDE_CTRL_ADDR = 'h0;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [7:0] ctrl;
  } precedence_override__out_t;


  // ---- Top-level hwif (HW write port) ---------------------------------------
  // Per HW-writable field: `<reg>_<field>` carries the candidate value;
  // `<reg>_<field>_we` is a single-cycle strobe that latches it into storage.
  // HW writes take precedence over SW writes on the same cycle.
  typedef struct packed {
    logic                                          ctrl_hw_wins_we;
    logic  ctrl_hw_wins;
    logic                                          ctrl_sw_wins_we;
    logic  ctrl_sw_wins;
  } precedence_override__in_t;

endpackage : precedence_override_pkg

// =============================================================================
// Module: precedence_override_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module precedence_override_regs
  import precedence_override_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output precedence_override__out_t hwif_out,

  // ---- HW write port --------------------------------------------------------
  input  precedence_override__in_t hwif_in
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [7:0] RD_MASK_CTRL = 8'h3;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [7:0] storage_ctrl;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_ctrl;
  logic rd_hit_ctrl;
  assign wr_hit_ctrl = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == PRECEDENCE_OVERRIDE_CTRL_ADDR);
  assign rd_hit_ctrl = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == PRECEDENCE_OVERRIDE_CTRL_ADDR);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[0] <= '0;
    end else if (hwif_in.ctrl_hw_wins_we) begin
      storage_ctrl[0] <= hwif_in.ctrl_hw_wins;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_ctrl[0] & ~cpuif_wr_biten[0]);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[1] <= '0;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[1] <= (cpuif_wr_data[1] & cpuif_wr_biten[1]) | (storage_ctrl[1] & ~cpuif_wr_biten[1]);
    end else if (hwif_in.ctrl_sw_wins_we) begin
      storage_ctrl[1] <= hwif_in.ctrl_sw_wins;
    end
  end



  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_ctrl | rd_hit_ctrl |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_ctrl: cpuif_rd_data_next = CPUIF_DATA_W'(storage_ctrl & RD_MASK_CTRL);
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.ctrl = storage_ctrl;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : precedence_override_regs

// =============================================================================
// UVM RAL package: precedence_override_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _PRECEDENCE_OVERRIDE_RAL_PKG_SV
`define _PRECEDENCE_OVERRIDE_RAL_PKG_SV

package precedence_override_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `ctrl` --------------------------------------
  class precedence_override_ctrl_reg extends uvm_reg;

    rand uvm_reg_field hw_wins;

    rand uvm_reg_field sw_wins;


    function new(string name = "precedence_override_ctrl_reg");
      super.new(name, 8, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.hw_wins = uvm_reg_field::type_id::create("hw_wins");
      this.hw_wins.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.sw_wins = uvm_reg_field::type_id::create("sw_wins");
      this.sw_wins.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (1),
        .access                  ("RW"),
        .volatile                (1'b1),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : precedence_override_ctrl_reg



  // ---- register block -------------------------------------------------------
  class precedence_override_reg_block extends uvm_reg_block;

    rand precedence_override_ctrl_reg ctrl;


    function new(string name = "precedence_override_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.ctrl = precedence_override_ctrl_reg::type_id::create("ctrl");
      this.ctrl.configure(this, null, "");
      this.ctrl.build();
      this.default_map.add_reg(this.ctrl, 8'h0, "RW");



      lock_model();
    endfunction

  endclass : precedence_override_reg_block

endpackage : precedence_override_ral_pkg

`endif // _PRECEDENCE_OVERRIDE_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `precedence_override_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `precedence_override_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _PRECEDENCE_OVERRIDE_RAL_SMOKE_SEQ_SV
`define _PRECEDENCE_OVERRIDE_RAL_SMOKE_SEQ_SV

package precedence_override_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import precedence_override_ral_pkg::*;

  class precedence_override_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(precedence_override_ral_smoke_seq)

    precedence_override_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "precedence_override_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // ctrl — RW: write pattern, read back, check equality.
      wdata = 'ha5;
      model.ctrl.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(ctrl) status=%s", status.name()))
      end
      model.ctrl.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(ctrl) status=%s", status.name()))
      end


    endtask

  endclass : precedence_override_ral_smoke_seq

endpackage : precedence_override_ral_smoke_pkg

`endif // _PRECEDENCE_OVERRIDE_RAL_SMOKE_SEQ_SV

