// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: device_pkg
// =============================================================================
package device_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic [23:0] value; // RW bits 23:0
  } foo_field_set_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] DEVICE_FOO_ADDR = 'h0;
  localparam logic [CPUIF_ADDR_W-1:0] DEVICE_BAR_ADDR_0 = 'h1;
  localparam logic [CPUIF_ADDR_W-1:0] DEVICE_BAR_ADDR_1 = 'h2;
  localparam logic [CPUIF_ADDR_W-1:0] DEVICE_BAR_ADDR_2 = 'h3;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [23:0] foo;
    logic [23:0] bar_0;
    logic [23:0] bar_1;
    logic [23:0] bar_2;
  } device__out_t;



endpackage : device_pkg

// =============================================================================
// Module: device_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module device_regs
  import device_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output device__out_t hwif_out
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [23:0] RD_MASK_FOO = 24'hffffff;
  localparam logic [23:0] RD_MASK_BAR = 24'hffffff;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [23:0] storage_foo;
  logic [23:0] storage_bar_0;
  logic [23:0] storage_bar_1;
  logic [23:0] storage_bar_2;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_foo;
  logic rd_hit_foo;
  assign wr_hit_foo = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == DEVICE_FOO_ADDR);
  assign rd_hit_foo = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == DEVICE_FOO_ADDR);
  logic wr_hit_bar_0;
  logic rd_hit_bar_0;
  assign wr_hit_bar_0 = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == DEVICE_BAR_ADDR_0);
  assign rd_hit_bar_0 = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == DEVICE_BAR_ADDR_0);
  logic wr_hit_bar_1;
  logic rd_hit_bar_1;
  assign wr_hit_bar_1 = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == DEVICE_BAR_ADDR_1);
  assign rd_hit_bar_1 = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == DEVICE_BAR_ADDR_1);
  logic wr_hit_bar_2;
  logic rd_hit_bar_2;
  assign wr_hit_bar_2 = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == DEVICE_BAR_ADDR_2);
  assign rd_hit_bar_2 = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == DEVICE_BAR_ADDR_2);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_foo[23:0] <= '0;
    end else if (wr_hit_foo) begin
      storage_foo[23:0] <= (cpuif_wr_data[23:0] & cpuif_wr_biten[23:0]) | (storage_foo[23:0] & ~cpuif_wr_biten[23:0]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_bar_0[23:0] <= 24'h123456;
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_bar_1[23:0] <= 24'h123456;
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_bar_2[23:0] <= 24'h123456;
    end
  end



  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_foo | rd_hit_foo |
      wr_hit_bar_0 | rd_hit_bar_0 |
      wr_hit_bar_1 | rd_hit_bar_1 |
      wr_hit_bar_2 | rd_hit_bar_2 |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_foo: cpuif_rd_data_next = CPUIF_DATA_W'(storage_foo & RD_MASK_FOO);
      rd_hit_bar_0: cpuif_rd_data_next = CPUIF_DATA_W'(storage_bar_0 & RD_MASK_BAR);
      rd_hit_bar_1: cpuif_rd_data_next = CPUIF_DATA_W'(storage_bar_1 & RD_MASK_BAR);
      rd_hit_bar_2: cpuif_rd_data_next = CPUIF_DATA_W'(storage_bar_2 & RD_MASK_BAR);
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.foo = storage_foo;
  assign hwif_out.bar_0 = storage_bar_0;
  assign hwif_out.bar_1 = storage_bar_1;
  assign hwif_out.bar_2 = storage_bar_2;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : device_regs

// =============================================================================
// UVM RAL package: device_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _DEVICE_RAL_PKG_SV
`define _DEVICE_RAL_PKG_SV

package device_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `foo` --------------------------------------
  class device_foo_reg extends uvm_reg;

    rand uvm_reg_field value;


    function new(string name = "device_foo_reg");
      super.new(name, 24, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.value = uvm_reg_field::type_id::create("value");
      this.value.configure(
        .parent                  (this),
        .size                    (24),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (24'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : device_foo_reg


  // ---- register `bar` --------------------------------------
  class device_bar_reg extends uvm_reg;

    rand uvm_reg_field value;


    function new(string name = "device_bar_reg");
      super.new(name, 24, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.value = uvm_reg_field::type_id::create("value");
      this.value.configure(
        .parent                  (this),
        .size                    (24),
        .lsb_pos                 (0),
        .access                  ("RO"),
        .volatile                (1'b0),
        .reset                   (24'h123456),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : device_bar_reg



  // ---- register block -------------------------------------------------------
  class device_reg_block extends uvm_reg_block;

    rand device_foo_reg foo;

    rand device_bar_reg bar;


    function new(string name = "device_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.foo = device_foo_reg::type_id::create("foo");
      this.foo.configure(this, null, "");
      this.foo.build();
      this.default_map.add_reg(this.foo, 8'h0, "RW");



      this.bar = device_bar_reg::type_id::create("bar");
      this.bar.configure(this, null, "");
      this.bar.build();
      this.default_map.add_reg(this.bar, 8'h1, "RO");



      lock_model();
    endfunction

  endclass : device_reg_block

endpackage : device_ral_pkg

`endif // _DEVICE_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `device_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `device_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _DEVICE_RAL_SMOKE_SEQ_SV
`define _DEVICE_RAL_SMOKE_SEQ_SV

package device_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import device_ral_pkg::*;

  class device_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(device_ral_smoke_seq)

    device_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "device_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // foo — RW: write pattern, read back, check equality.
      wdata = 'ha55aa5;
      model.foo.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(foo) status=%s", status.name()))
      end
      model.foo.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(foo) status=%s", status.name()))
      end



      // bar — RO: read-only smoke (no write).
      model.bar.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(bar) status=%s", status.name()))
      end


    endtask

  endclass : device_ral_smoke_seq

endpackage : device_ral_smoke_pkg

`endif // _DEVICE_RAL_SMOKE_SEQ_SV

