// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: axi_4_lite_basic_pkg
// =============================================================================
package axi_4_lite_basic_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic  enable; // RW bits bit 0
    logic [15:0] count; // RW bits 31:16
  } ctrl_fields_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] AXI_4_LITE_BASIC_CTRL_ADDR = 'h0;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [31:0] ctrl;
  } axi_4_lite_basic__out_t;



endpackage : axi_4_lite_basic_pkg

// =============================================================================
// Module: axi_4_lite_basic_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module axi_4_lite_basic_regs
  import axi_4_lite_basic_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output axi_4_lite_basic__out_t hwif_out
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [31:0] RD_MASK_CTRL = 32'hffff0001;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [31:0] storage_ctrl;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_ctrl;
  logic rd_hit_ctrl;
  assign wr_hit_ctrl = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == AXI_4_LITE_BASIC_CTRL_ADDR);
  assign rd_hit_ctrl = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == AXI_4_LITE_BASIC_CTRL_ADDR);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[0] <= '0;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_ctrl[0] & ~cpuif_wr_biten[0]);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[31:16] <= '0;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[31:16] <= (cpuif_wr_data[31:16] & cpuif_wr_biten[31:16]) | (storage_ctrl[31:16] & ~cpuif_wr_biten[31:16]);
    end
  end



  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_ctrl | rd_hit_ctrl |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_ctrl: cpuif_rd_data_next = CPUIF_DATA_W'(storage_ctrl & RD_MASK_CTRL);
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.ctrl = storage_ctrl;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : axi_4_lite_basic_regs

// =============================================================================
// AXI4-Lite → native CPUIF wrapper.
//
// Separate write and read FSMs, each at most one outstanding request:
//   W path: IDLE → REQ → RESP → IDLE
//   R path: IDLE → REQ → RESP → IDLE
//
// Both paths share a single CPUIF; on simultaneous contention the write
// arbitrates first (canonical CSR convention). Decision 6 holds — bus-side
// SLVERR comes from the regs module's cpuif_*_err only; unmapped addresses
// outside the regblock allocation are the interconnect's responsibility.
//
// AWPROT/ARPROT carried but ignored (CSR is privilege-agnostic).
// =============================================================================
module axi_4_lite_basic_axi4lite
  import axi_4_lite_basic_pkg::*;
(
  input  logic                          aclk,
  input  logic                          aresetn,

  // ---- AW ----------------------------------------------------------------
  input  logic                          awvalid,
  output logic                          awready,
  input  logic [CPUIF_ADDR_W-1:0]       awaddr,
  input  logic [2:0]                    awprot,

  // ---- W  ----------------------------------------------------------------
  input  logic                          wvalid,
  output logic                          wready,
  input  logic [CPUIF_DATA_W-1:0]       wdata,
  input  logic [CPUIF_DATA_W/8-1:0]     wstrb,

  // ---- B  ----------------------------------------------------------------
  output logic                          bvalid,
  input  logic                          bready,
  output logic [1:0]                    bresp,

  // ---- AR ----------------------------------------------------------------
  input  logic                          arvalid,
  output logic                          arready,
  input  logic [CPUIF_ADDR_W-1:0]       araddr,
  input  logic [2:0]                    arprot,

  // ---- R  ----------------------------------------------------------------
  output logic                          rvalid,
  input  logic                          rready,
  output logic [CPUIF_DATA_W-1:0]       rdata,
  output logic [1:0]                    rresp,

  output axi_4_lite_basic__out_t          hwif_out
);

  // Protection signals are informational only on a CSR block; tie off any
  // lint about unused inputs.
  logic _unused_prot;
  assign _unused_prot = |awprot ^ |arprot;

  // ---------------------------------------------------------------------------
  // Native CPUIF wires
  // ---------------------------------------------------------------------------
  logic                          cpuif_req;
  logic                          cpuif_req_is_wr;
  logic [CPUIF_ADDR_W-1:0]       cpuif_addr;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten;
  logic                          cpuif_rd_ack;
  logic                          cpuif_rd_err;
  logic [CPUIF_DATA_W-1:0]       cpuif_rd_data;
  logic                          cpuif_wr_ack;
  logic                          cpuif_wr_err;

  // ---------------------------------------------------------------------------
  // Write FSM
  // ---------------------------------------------------------------------------
  typedef enum logic [1:0] {W_IDLE, W_REQ, W_RESP} w_state_e;
  w_state_e w_state;
  logic [CPUIF_ADDR_W-1:0] w_addr_q;
  logic [CPUIF_DATA_W-1:0] w_data_q;
  logic [CPUIF_DATA_W-1:0] w_biten_q;
  logic                    w_err_q;

  // WSTRB → wr_biten fanout into a temporary so the registered version
  // captures the strobe pattern at handshake time.
  logic [CPUIF_DATA_W-1:0] wstrb_expanded;
  genvar i;
  generate
    for (i = 0; i < CPUIF_DATA_W/8; i = i + 1) begin : g_strb
      assign wstrb_expanded[i*8 +: 8] = {8{wstrb[i]}};
    end
  endgenerate

  always_ff @(posedge aclk) begin
    if (!aresetn) begin
      w_state   <= W_IDLE;
      w_addr_q  <= '0;
      w_data_q  <= '0;
      w_biten_q <= '0;
      w_err_q   <= 1'b0;
    end else begin
      unique case (w_state)
        W_IDLE: begin
          if (awvalid && wvalid) begin
            w_addr_q  <= awaddr;
            w_data_q  <= wdata;
            w_biten_q <= wstrb_expanded;
            w_state   <= W_REQ;
          end
        end
        W_REQ: begin
          if (cpuif_wr_ack) begin
            w_err_q <= cpuif_wr_err;
            w_state <= W_RESP;
          end
        end
        W_RESP: begin
          if (bready) w_state <= W_IDLE;
        end
        default: w_state <= W_IDLE;
      endcase
    end
  end

  assign awready = (w_state == W_IDLE);
  assign wready  = (w_state == W_IDLE);
  assign bvalid  = (w_state == W_RESP);
  assign bresp   = w_err_q ? 2'b10 : 2'b00; // SLVERR : OKAY

  // ---------------------------------------------------------------------------
  // Read FSM
  // ---------------------------------------------------------------------------
  typedef enum logic [1:0] {R_IDLE, R_REQ, R_RESP} r_state_e;
  r_state_e r_state;
  logic [CPUIF_ADDR_W-1:0] r_addr_q;
  logic [CPUIF_DATA_W-1:0] r_data_q;
  logic                    r_err_q;

  always_ff @(posedge aclk) begin
    if (!aresetn) begin
      r_state  <= R_IDLE;
      r_addr_q <= '0;
      r_data_q <= '0;
      r_err_q  <= 1'b0;
    end else begin
      unique case (r_state)
        R_IDLE: begin
          if (arvalid) begin
            r_addr_q <= araddr;
            r_state  <= R_REQ;
          end
        end
        R_REQ: begin
          if (cpuif_rd_ack) begin
            r_data_q <= cpuif_rd_data;
            r_err_q  <= cpuif_rd_err;
            r_state  <= R_RESP;
          end
        end
        R_RESP: begin
          if (rready) r_state <= R_IDLE;
        end
        default: r_state <= R_IDLE;
      endcase
    end
  end

  assign arready = (r_state == R_IDLE);
  assign rvalid  = (r_state == R_RESP);
  assign rdata   = r_data_q;
  assign rresp   = r_err_q ? 2'b10 : 2'b00;

  // ---------------------------------------------------------------------------
  // CPUIF arbitration — writes win on simultaneous contention.
  // ---------------------------------------------------------------------------
  logic w_wants_cpuif, r_wants_cpuif;
  assign w_wants_cpuif = (w_state == W_REQ);
  assign r_wants_cpuif = (r_state == R_REQ);

  assign cpuif_req       = w_wants_cpuif | r_wants_cpuif;
  assign cpuif_req_is_wr = w_wants_cpuif;
  assign cpuif_addr      = w_wants_cpuif ? w_addr_q  : r_addr_q;
  assign cpuif_wr_data   = w_data_q;
  assign cpuif_wr_biten  = w_biten_q;

  axi_4_lite_basic_regs u_regs (
    .clk            (aclk),
    .rst_n          (aresetn),
    .cpuif_req      (cpuif_req),
    .cpuif_req_is_wr(cpuif_req_is_wr),
    .cpuif_addr     (cpuif_addr),
    .cpuif_wr_data  (cpuif_wr_data),
    .cpuif_wr_biten (cpuif_wr_biten),
    .cpuif_rd_ack   (cpuif_rd_ack),
    .cpuif_rd_err   (cpuif_rd_err),
    .cpuif_rd_data  (cpuif_rd_data),
    .cpuif_wr_ack   (cpuif_wr_ack),
    .cpuif_wr_err   (cpuif_wr_err),
    .hwif_out       (hwif_out)
  );

`ifdef ASSERT_ON
  // ---------------------------------------------------------------------------
  // AXI4-Lite protocol stability checks. The spec is single-beat by
  // construction (no AWLEN / ARLEN exists on AXI4-Lite), so the only thing
  // worth asserting in the wrapper is handshake stability: VALID must stay
  // high until READY accepts it.
  // ---------------------------------------------------------------------------
  property p_aw_stable;
    @(posedge aclk) disable iff (!aresetn)
      (awvalid && !awready) |=> awvalid;
  endproperty
  property p_w_stable;
    @(posedge aclk) disable iff (!aresetn)
      (wvalid && !wready) |=> wvalid;
  endproperty
  property p_ar_stable;
    @(posedge aclk) disable iff (!aresetn)
      (arvalid && !arready) |=> arvalid;
  endproperty
  property p_b_stable;
    @(posedge aclk) disable iff (!aresetn)
      (bvalid && !bready) |=> bvalid;
  endproperty
  property p_r_stable;
    @(posedge aclk) disable iff (!aresetn)
      (rvalid && !rready) |=> rvalid;
  endproperty

  a_aw_stable: assert property (p_aw_stable) else $error("aw VALID dropped pre-handshake");
  a_w_stable:  assert property (p_w_stable)  else $error("w VALID dropped pre-handshake");
  a_ar_stable: assert property (p_ar_stable) else $error("ar VALID dropped pre-handshake");
  a_b_stable:  assert property (p_b_stable)  else $error("b VALID dropped pre-handshake");
  a_r_stable:  assert property (p_r_stable)  else $error("r VALID dropped pre-handshake");
`endif

endmodule : axi_4_lite_basic_axi4lite

// =============================================================================
// UVM RAL package: axi_4_lite_basic_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _AXI_4_LITE_BASIC_RAL_PKG_SV
`define _AXI_4_LITE_BASIC_RAL_PKG_SV

package axi_4_lite_basic_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `ctrl` --------------------------------------
  class axi_4_lite_basic_ctrl_reg extends uvm_reg;

    rand uvm_reg_field enable;

    rand uvm_reg_field count;


    function new(string name = "axi_4_lite_basic_ctrl_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.enable = uvm_reg_field::type_id::create("enable");
      this.enable.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.count = uvm_reg_field::type_id::create("count");
      this.count.configure(
        .parent                  (this),
        .size                    (16),
        .lsb_pos                 (16),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (16'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : axi_4_lite_basic_ctrl_reg



  // ---- register block -------------------------------------------------------
  class axi_4_lite_basic_reg_block extends uvm_reg_block;

    rand axi_4_lite_basic_ctrl_reg ctrl;


    function new(string name = "axi_4_lite_basic_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.ctrl = axi_4_lite_basic_ctrl_reg::type_id::create("ctrl");
      this.ctrl.configure(this, null, "");
      this.ctrl.build();
      this.default_map.add_reg(this.ctrl, 8'h0, "RW");



      lock_model();
    endfunction

  endclass : axi_4_lite_basic_reg_block

endpackage : axi_4_lite_basic_ral_pkg

`endif // _AXI_4_LITE_BASIC_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `axi_4_lite_basic_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `axi_4_lite_basic_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _AXI_4_LITE_BASIC_RAL_SMOKE_SEQ_SV
`define _AXI_4_LITE_BASIC_RAL_SMOKE_SEQ_SV

package axi_4_lite_basic_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import axi_4_lite_basic_ral_pkg::*;

  class axi_4_lite_basic_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(axi_4_lite_basic_ral_smoke_seq)

    axi_4_lite_basic_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "axi_4_lite_basic_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // ctrl — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.ctrl.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(ctrl) status=%s", status.name()))
      end
      model.ctrl.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(ctrl) status=%s", status.name()))
      end


    endtask

  endclass : axi_4_lite_basic_ral_smoke_seq

endpackage : axi_4_lite_basic_ral_smoke_pkg

`endif // _AXI_4_LITE_BASIC_RAL_SMOKE_SEQ_SV

