// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: apb_4_basic_pkg
// =============================================================================
package apb_4_basic_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic  enable; // RW bits bit 0
    logic [6:0] mode; // RW bits 7:1
    logic [15:0] threshold; // RW bits 31:16
  } ctrl_fields_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] APB_4_BASIC_CTRL_ADDR = 'h0;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [31:0] ctrl;
  } apb_4_basic__out_t;



endpackage : apb_4_basic_pkg

// =============================================================================
// Module: apb_4_basic_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module apb_4_basic_regs
  import apb_4_basic_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output apb_4_basic__out_t hwif_out
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [31:0] RD_MASK_CTRL = 32'hffff00ff;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [31:0] storage_ctrl;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_ctrl;
  logic rd_hit_ctrl;
  assign wr_hit_ctrl = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == APB_4_BASIC_CTRL_ADDR);
  assign rd_hit_ctrl = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == APB_4_BASIC_CTRL_ADDR);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[0] <= '0;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[0] <= (cpuif_wr_data[0] & cpuif_wr_biten[0]) | (storage_ctrl[0] & ~cpuif_wr_biten[0]);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[7:1] <= '0;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[7:1] <= (cpuif_wr_data[7:1] & cpuif_wr_biten[7:1]) | (storage_ctrl[7:1] & ~cpuif_wr_biten[7:1]);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_ctrl[31:16] <= '0;
    end else if (wr_hit_ctrl) begin
      storage_ctrl[31:16] <= (cpuif_wr_data[31:16] & cpuif_wr_biten[31:16]) | (storage_ctrl[31:16] & ~cpuif_wr_biten[31:16]);
    end
  end



  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_ctrl | rd_hit_ctrl |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_ctrl: cpuif_rd_data_next = CPUIF_DATA_W'(storage_ctrl & RD_MASK_CTRL);
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.ctrl = storage_ctrl;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : apb_4_basic_regs

// =============================================================================
// APB4 → native CPUIF wrapper.
//
// Identical to APB3 plus:
//   - PSTRB[CPUIF_DATA_W/8-1:0] per-byte write strobe, fanned out to
//     cpuif_wr_biten (each strobe bit replicated across its byte).
//   - PPROT[2:0] protection signal — carried but unused for CSR.
//
// PSEL+PENABLE+~PREADY drives cpuif_req. PSLVERR is set from cpuif_*_err.
// =============================================================================
module apb_4_basic_apb4
  import apb_4_basic_pkg::*;
(
  input  logic                          pclk,
  input  logic                          presetn,

  input  logic                          psel,
  input  logic                          penable,
  input  logic                          pwrite,
  input  logic [CPUIF_ADDR_W-1:0]       paddr,
  input  logic [CPUIF_DATA_W-1:0]       pwdata,
  input  logic [CPUIF_DATA_W/8-1:0]     pstrb,
  input  logic [2:0]                    pprot,

  output logic [CPUIF_DATA_W-1:0]       prdata,
  output logic                          pready,
  output logic                          pslverr,

  output apb_4_basic__out_t          hwif_out
);

  // pprot is informational only on a CSR block; ignore.
  logic _unused_pprot;
  assign _unused_pprot = |pprot;

  // ---------------------------------------------------------------------------
  // Native CPUIF wires
  // ---------------------------------------------------------------------------
  logic                          cpuif_req;
  logic                          cpuif_req_is_wr;
  logic [CPUIF_ADDR_W-1:0]       cpuif_addr;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten;
  logic                          cpuif_rd_ack;
  logic                          cpuif_rd_err;
  logic [CPUIF_DATA_W-1:0]       cpuif_rd_data;
  logic                          cpuif_wr_ack;
  logic                          cpuif_wr_err;

  // ---------------------------------------------------------------------------
  // PSTRB → wr_biten fanout. Each byte-strobe bit drives all 8 bits of its byte.
  // ---------------------------------------------------------------------------
  genvar i;
  generate
    for (i = 0; i < CPUIF_DATA_W/8; i = i + 1) begin : g_strb
      assign cpuif_wr_biten[i*8 +: 8] = {8{pstrb[i]}};
    end
  endgenerate

  // ---------------------------------------------------------------------------
  // APB → CPUIF: request fires on the ACCESS phase (psel & penable). pready
  // gates the request so we only present one cycle per transfer.
  // ---------------------------------------------------------------------------
  assign cpuif_req       = psel & penable & ~pready;
  assign cpuif_req_is_wr = pwrite;
  assign cpuif_addr      = paddr;
  assign cpuif_wr_data   = pwdata;

  // ---------------------------------------------------------------------------
  // CPUIF → APB.
  // ---------------------------------------------------------------------------
  assign pready  = cpuif_rd_ack | cpuif_wr_ack;
  assign pslverr = cpuif_rd_err | cpuif_wr_err;
  assign prdata  = cpuif_rd_data;

  apb_4_basic_regs u_regs (
    .clk            (pclk),
    .rst_n          (presetn),
    .cpuif_req      (cpuif_req),
    .cpuif_req_is_wr(cpuif_req_is_wr),
    .cpuif_addr     (cpuif_addr),
    .cpuif_wr_data  (cpuif_wr_data),
    .cpuif_wr_biten (cpuif_wr_biten),
    .cpuif_rd_ack   (cpuif_rd_ack),
    .cpuif_rd_err   (cpuif_rd_err),
    .cpuif_rd_data  (cpuif_rd_data),
    .cpuif_wr_ack   (cpuif_wr_ack),
    .cpuif_wr_err   (cpuif_wr_err),
    .hwif_out       (hwif_out)
  );

endmodule : apb_4_basic_apb4

// =============================================================================
// UVM RAL package: apb_4_basic_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _APB_4_BASIC_RAL_PKG_SV
`define _APB_4_BASIC_RAL_PKG_SV

package apb_4_basic_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `ctrl` --------------------------------------
  class apb_4_basic_ctrl_reg extends uvm_reg;

    rand uvm_reg_field enable;

    rand uvm_reg_field mode;

    rand uvm_reg_field threshold;


    function new(string name = "apb_4_basic_ctrl_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.enable = uvm_reg_field::type_id::create("enable");
      this.enable.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.mode = uvm_reg_field::type_id::create("mode");
      this.mode.configure(
        .parent                  (this),
        .size                    (7),
        .lsb_pos                 (1),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (7'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.threshold = uvm_reg_field::type_id::create("threshold");
      this.threshold.configure(
        .parent                  (this),
        .size                    (16),
        .lsb_pos                 (16),
        .access                  ("RW"),
        .volatile                (1'b0),
        .reset                   (16'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : apb_4_basic_ctrl_reg



  // ---- register block -------------------------------------------------------
  class apb_4_basic_reg_block extends uvm_reg_block;

    rand apb_4_basic_ctrl_reg ctrl;


    function new(string name = "apb_4_basic_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.ctrl = apb_4_basic_ctrl_reg::type_id::create("ctrl");
      this.ctrl.configure(this, null, "");
      this.ctrl.build();
      this.default_map.add_reg(this.ctrl, 8'h0, "RW");



      lock_model();
    endfunction

  endclass : apb_4_basic_reg_block

endpackage : apb_4_basic_ral_pkg

`endif // _APB_4_BASIC_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `apb_4_basic_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `apb_4_basic_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _APB_4_BASIC_RAL_SMOKE_SEQ_SV
`define _APB_4_BASIC_RAL_SMOKE_SEQ_SV

package apb_4_basic_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import apb_4_basic_ral_pkg::*;

  class apb_4_basic_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(apb_4_basic_ral_smoke_seq)

    apb_4_basic_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "apb_4_basic_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // ctrl — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.ctrl.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(ctrl) status=%s", status.name()))
      end
      model.ctrl.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(ctrl) status=%s", status.name()))
      end


    endtask

  endclass : apb_4_basic_ral_smoke_seq

endpackage : apb_4_basic_ral_smoke_pkg

`endif // _APB_4_BASIC_RAL_SMOKE_SEQ_SV

