// This file is auto-generated by the SystemVerilog snapshot test harness.
// Run `cargo run --bin device-driver-tests -- accept` to regenerate.

// This code was generated using device-driver `2.0.0-alpha.1` (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
// a tool distributed under MIT OR Apache-2.0 by Dion Dokter <dev@diondokter.nl>
// This version was built for xxxx-xxxx-xxxx using rustc 1.xx.x (xxxxxxxxx xxxx-xx-xx)
// 
// For more information about device-driver, visit the website: https://device-driver.com

// -----------------------------------------------------------------------------
// Generated by device-driver compiler — SystemVerilog target.
// Do not edit by hand. Regenerate from the DDSL source.
// -----------------------------------------------------------------------------
//
// Internal CPUIF (Decision 1 + 2): per-bit wr_biten; split rd_ack/wr_ack.
// Reset (Decision 3): synchronous active-low rst_n.
// Naming (Decision 4): <dev>_regs / <dev>_pkg / <DEV>_<REG>_ADDR.
//
// =============================================================================
// Package: sva_basic_pkg
// =============================================================================
package sva_basic_pkg;

  // ---- Bus parameters -------------------------------------------------------
  localparam int unsigned CPUIF_ADDR_W = 8;
  localparam int unsigned CPUIF_DATA_W = 32;

  // ---- Per-fieldset packed structs ------------------------------------------
  typedef struct packed {
    logic [7:0] major; // RO bits 31:24
    logic [7:0] minor; // RO bits 23:16
    logic [15:0] patch; // RO bits 15:0
  } version_fields_t;
  typedef struct packed {
    logic  error; // RW bits bit 0
    logic  warn; // RW bits bit 1
  } status_fields_t;

  // ---- Register address constants -------------------------------------------
  localparam logic [CPUIF_ADDR_W-1:0] SVA_BASIC_STATUS_ADDR = 'h0;
  localparam logic [CPUIF_ADDR_W-1:0] SVA_BASIC_VERSION_ADDR = 'h4;

  // ---- Command strobe address constants -------------------------------------

  // ---- Buffer (FIFO) address constants --------------------------------------

  // ---- Top-level hwif (HW observation port) ---------------------------------
  // Raw register storage values, surrounded by reserved-bit zeros (if any).
  // Project named fields via the per-fieldset struct typedef above:
  //   <fs>_t f = <fs>_t'(hwif_out.<reg>);
  typedef struct packed {
    logic [31:0] status;
    logic [31:0] version;
  } sva_basic__out_t;



endpackage : sva_basic_pkg

// =============================================================================
// Module: sva_basic_regs
//
// Internal CPUIF (see SYSTEMVERILOG_DECISIONS.md, Decision 1+2):
//   - Per-bit cpuif_wr_biten (not byte wstrb)
//   - Split rd_ack / wr_ack, in-order, no IDs
//   - Single outstanding request per direction
//   - cpuif_rd_data is registered so it remains stable the cycle
//     cpuif_rd_ack pulses. Wrapper modules and downstream consumers
//     may sample {rd_data, rd_ack} together without timing races.
// =============================================================================
module sva_basic_regs
  import sva_basic_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,

  // ---- Internal CPUIF -------------------------------------------------------
  input  logic                          cpuif_req,
  input  logic                          cpuif_req_is_wr,
  input  logic [CPUIF_ADDR_W-1:0]       cpuif_addr,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,

  output logic                          cpuif_rd_ack,
  output logic                          cpuif_rd_err,
  output logic [CPUIF_DATA_W-1:0]       cpuif_rd_data,

  output logic                          cpuif_wr_ack,
  output logic                          cpuif_wr_err,

  // ---- HW observation port --------------------------------------------------
  output sva_basic__out_t hwif_out
);

  // ---------------------------------------------------------------------------
  // Per-register read masks (RW+RO bits exposed; WO bits return zero on read).
  // Widened to the full word when `reserved-behavior` is `ro_preserve` or
  // `rw_storage`. External registers skip the mask — user RTL drives rd_data.
  // ---------------------------------------------------------------------------
  localparam logic [31:0] RD_MASK_STATUS = 32'h3;
  localparam logic [31:0] RD_MASK_VERSION = 32'hffffffff;

  // ---------------------------------------------------------------------------
  // Per-register storage (skipped for `external` registers — no flop)
  // ---------------------------------------------------------------------------
  logic [31:0] storage_status;
  logic [31:0] storage_version;

  // ---------------------------------------------------------------------------
  // Address decode (per-instance write/read hits)
  // ---------------------------------------------------------------------------
  logic wr_hit_status;
  logic rd_hit_status;
  assign wr_hit_status = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == SVA_BASIC_STATUS_ADDR);
  assign rd_hit_status = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == SVA_BASIC_STATUS_ADDR);
  logic wr_hit_version;
  logic rd_hit_version;
  assign wr_hit_version = cpuif_req &&  cpuif_req_is_wr && (cpuif_addr == SVA_BASIC_VERSION_ADDR);
  assign rd_hit_version = cpuif_req && !cpuif_req_is_wr && (cpuif_addr == SVA_BASIC_VERSION_ADDR);

  // ---------------------------------------------------------------------------
  // Storage flops — one `always_ff` per field. Each field's slice has a
  // private precedence cascade: reset → HW write (`hwif_in.<f>_we`)
  //                             → SW write (on-write) → SW read modifier.
  // `external` registers are skipped (no storage).
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_status[0] <= 1'h0;
    end else if (wr_hit_status) begin
      storage_status[0] <= storage_status[0] & ~(cpuif_wr_data[0] & cpuif_wr_biten[0]);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_status[1] <= 1'h0;
    end else if (wr_hit_status) begin
      storage_status[1] <= storage_status[1] & ~(cpuif_wr_data[1] & cpuif_wr_biten[1]);
    end
  end


  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_version[31:24] <= 8'hca;
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_version[23:16] <= 8'hfe;
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      storage_version[15:0] <= 16'hbabe;
    end
  end



  // ---------------------------------------------------------------------------
  // Read mux + decode-hit aggregation
  // ---------------------------------------------------------------------------
  logic any_hit;
  assign any_hit =
      wr_hit_status | rd_hit_status |
      wr_hit_version | rd_hit_version |
      1'b0;

  // Combinational read mux. Captured into `cpuif_rd_data` on the next
  // posedge so the registered output remains stable the cycle
  // `cpuif_rd_ack` pulses (otherwise wrapper handshakes that gate
  // `cpuif_req` on `~pready` would see the mux collapse to '0).
  logic [CPUIF_DATA_W-1:0] cpuif_rd_data_next;
  always_comb begin
    cpuif_rd_data_next = '0;
    unique case (1'b1)
      rd_hit_status: cpuif_rd_data_next = CPUIF_DATA_W'(storage_status & RD_MASK_STATUS);
      rd_hit_version: cpuif_rd_data_next = CPUIF_DATA_W'(storage_version & RD_MASK_VERSION);
      default: cpuif_rd_data_next = '0;
    endcase
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_data <= '0;
    end else if (cpuif_req && !cpuif_req_is_wr) begin
      cpuif_rd_data <= cpuif_rd_data_next;
    end
  end

  // ---------------------------------------------------------------------------
  // Ack / err — SLVERR when request hits no register inside this block
  // ---------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      cpuif_rd_ack <= 1'b0;
      cpuif_wr_ack <= 1'b0;
      cpuif_rd_err <= 1'b0;
      cpuif_wr_err <= 1'b0;
    end else begin
      cpuif_rd_ack <= cpuif_req && !cpuif_req_is_wr;
      cpuif_wr_ack <= cpuif_req &&  cpuif_req_is_wr;
      cpuif_rd_err <= cpuif_req && !cpuif_req_is_wr && !any_hit;
      cpuif_wr_err <= cpuif_req &&  cpuif_req_is_wr && !any_hit;
    end
  end

  // ---------------------------------------------------------------------------
  // HW observation assignments. Internal regs expose `hwif_out.<reg>` =
  // storage; external regs expose `<reg>_ext_wr_hit` + `<reg>_ext_wr_data`
  // instead so user RTL sees the bus transaction directly.
  // ---------------------------------------------------------------------------
  assign hwif_out.status = storage_status;
  assign hwif_out.version = storage_version;

  // ---------------------------------------------------------------------------
  // Skipped block-method kinds (Rust-target-only constructs)
  // ---------------------------------------------------------------------------

endmodule : sva_basic_regs

// =============================================================================
// APB3 → native CPUIF wrapper.
//
// Handshake: psel + penable starts a transaction. We assert pready as soon as
// the regs module's cpuif_*_ack returns (single-cycle for now). pslverr is
// driven by the regs module's wr_err / rd_err.
//
// Note: APB3 has no per-byte write strobe. wdata is fanned out to every bit
// of cpuif_wr_biten — every-bit-enabled writes match APB's "the whole word
// is what got written" semantics.
// =============================================================================
module sva_basic_apb3
  import sva_basic_pkg::*;
(
  input  logic                          pclk,
  input  logic                          presetn,

  input  logic                          psel,
  input  logic                          penable,
  input  logic                          pwrite,
  input  logic [CPUIF_ADDR_W-1:0]       paddr,
  input  logic [CPUIF_DATA_W-1:0]       pwdata,

  output logic [CPUIF_DATA_W-1:0]       prdata,
  output logic                          pready,
  output logic                          pslverr,

  output sva_basic__out_t          hwif_out
);

  // ---------------------------------------------------------------------------
  // Native CPUIF wires
  // ---------------------------------------------------------------------------
  logic                          cpuif_req;
  logic                          cpuif_req_is_wr;
  logic [CPUIF_ADDR_W-1:0]       cpuif_addr;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data;
  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten;
  logic                          cpuif_rd_ack;
  logic                          cpuif_rd_err;
  logic [CPUIF_DATA_W-1:0]       cpuif_rd_data;
  logic                          cpuif_wr_ack;
  logic                          cpuif_wr_err;

  // ---------------------------------------------------------------------------
  // APB → CPUIF translation. Request goes out on the ACCESS phase (psel+penable);
  // ready latches in the cycle after, and the next access starts after pready
  // is sampled, so we don't need a per-request FIFO.
  // ---------------------------------------------------------------------------
  assign cpuif_req       = psel & penable & ~pready;
  assign cpuif_req_is_wr = pwrite;
  assign cpuif_addr      = paddr;
  assign cpuif_wr_data   = pwdata;
  assign cpuif_wr_biten  = {CPUIF_DATA_W{1'b1}}; // APB3 has no per-byte strobe

  // ---------------------------------------------------------------------------
  // CPUIF → APB. Ack from either direction satisfies pready; err from either
  // direction satisfies pslverr.
  // ---------------------------------------------------------------------------
  assign pready  = cpuif_rd_ack | cpuif_wr_ack;
  assign pslverr = cpuif_rd_err | cpuif_wr_err;
  assign prdata  = cpuif_rd_data;

  // ---------------------------------------------------------------------------
  // Inner regs module
  // ---------------------------------------------------------------------------
  sva_basic_regs u_regs (
    .clk            (pclk),
    .rst_n          (presetn),
    .cpuif_req      (cpuif_req),
    .cpuif_req_is_wr(cpuif_req_is_wr),
    .cpuif_addr     (cpuif_addr),
    .cpuif_wr_data  (cpuif_wr_data),
    .cpuif_wr_biten (cpuif_wr_biten),
    .cpuif_rd_ack   (cpuif_rd_ack),
    .cpuif_rd_err   (cpuif_rd_err),
    .cpuif_rd_data  (cpuif_rd_data),
    .cpuif_wr_ack   (cpuif_wr_ack),
    .cpuif_wr_err   (cpuif_wr_err),
    .hwif_out       (hwif_out)
  );

endmodule : sva_basic_apb3

// =============================================================================
// Module: sva_basic_sva
//
// SystemVerilog Assertions (SVA) checker module. Drop in beside
// `sva_basic_regs` via the companion bind snippet
// (`sva_basic_sva_bind.svh`). Each category is opt-in
// via device-level `sv-assert-*` flags; only enabled categories appear here.
//
// Enabled in this build:
//   * reset           — storage equals reset value while `!rst_n`
//   * decode_mutex    — at most one wr_hit_/rd_hit_ asserts per cycle
//   * w1c             — `on-write: clear` fields clear written bits next cycle
//   * ro_invariance   — fully-RO fields (SW RO + HW RO) hold reset value
// =============================================================================
module sva_basic_sva
  import sva_basic_pkg::*;
(
  input  logic                          clk,
  input  logic                          rst_n,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_data,
  input  logic [CPUIF_DATA_W-1:0]       cpuif_wr_biten,
  input  logic                wr_hit_status,
  input  logic                rd_hit_status,
  input  logic [31:0]                storage_status,
  input  logic                wr_hit_version,
  input  logic                rd_hit_version,
  input  logic [31:0]                storage_version
);


  // ---- decode_mutex --------------------------------------------------------
  // No two hit signals may assert simultaneously. (`$onehot0` tolerates the
  // all-zero idle case.)
  property p_decode_mutex;
    @(posedge clk) disable iff (!rst_n)
      $onehot0({ wr_hit_status, rd_hit_status, wr_hit_version, rd_hit_version });
  endproperty
  a_decode_mutex: assert property (p_decode_mutex)
    else $error("decode mutex violated");



  // ---- reset ---------------------------------------------------------------
  // Storage holds its reset value during the assertion of rst_n. Per-register
  // because reset literals are per-register.

  a_reset_status: assert property (
    @(posedge clk) (!rst_n) |-> ##1 (storage_status == 32'h0));

  a_reset_version: assert property (
    @(posedge clk) (!rst_n) |-> ##1 (storage_version == 32'hcafebabe));




  // ---- w1c -----------------------------------------------------------------
  // After a write transaction that hits the register, every W1C field's bits
  // were cleared exactly where the previous-cycle wdata&biten said `1`.

  a_w1c_status_error: assert property (
    @(posedge clk) disable iff (!rst_n)
      $past(wr_hit_status) |->
        (storage_status[0] === ($past(storage_status[0]) & ~$past(cpuif_wr_data[0] & cpuif_wr_biten[0]))));

  a_w1c_status_warn: assert property (
    @(posedge clk) disable iff (!rst_n)
      $past(wr_hit_status) |->
        (storage_status[1] === ($past(storage_status[1]) & ~$past(cpuif_wr_data[1] & cpuif_wr_biten[1]))));




  // ---- ro_invariance -------------------------------------------------------
  // Fully-RO fields (SW RO + HW RO, no hw-set/hw-clr, no intr) hold their
  // reset value indefinitely after reset deasserts.

  a_ro_version_major: assert property (
    @(posedge clk) (rst_n) |-> (storage_version[31:24] == 8'hca));

  a_ro_version_minor: assert property (
    @(posedge clk) (rst_n) |-> (storage_version[23:16] == 8'hfe));

  a_ro_version_patch: assert property (
    @(posedge clk) (rst_n) |-> (storage_version[15:0] == 16'hbabe));



  // Sink any inputs that aren't referenced by an enabled category — keeps
  // verilator quiet about unused ports when only one category is on.
  wire _unused_sva;
  assign _unused_sva = ^{clk, rst_n, cpuif_wr_data, cpuif_wr_biten, wr_hit_status, rd_hit_status, storage_status, wr_hit_version, rd_hit_version, storage_version};

endmodule : sva_basic_sva

// =============================================================================
// SVA bind snippet for `sva_basic_regs`.
//
// Include this header into any compilation unit that already sees both
// `sva_basic_regs` and `sva_basic_sva` — for example, the
// testbench top-level. The bind attaches one checker instance to every
// elaboration of `sva_basic_regs` and ties the checker
// ports to like-named signals in that scope via `.*`.
// =============================================================================
`ifndef _SVA_BASIC_SVA_BIND_SVH
`define _SVA_BASIC_SVA_BIND_SVH

bind sva_basic_regs sva_basic_sva u_sva (.*);

`endif // _SVA_BASIC_SVA_BIND_SVH

// =============================================================================
// UVM RAL package: sva_basic_ral_pkg
//
// Generated UVM register model for verification-team consumption. Adds:
//   * One `<dev>_<reg>_reg` (`uvm_reg`) subclass per register
//   * One `<dev>_reg_block` (`uvm_reg_block`) subclass tying them together
//   * Per-field `uvm_reg_field` declarations with UVM access strings
//     derived from DDSL access + on-write modifiers
//   * Optional backdoor wiring via `add_hdl_path_slice` (only when the
//     device sets `sv-hdl-path-prefix`)
//
// Compile with `+incdir+$UVM_HOME/src $UVM_HOME/src/uvm.sv`. Tested at
// snapshot level only — OSS CI cannot run UVM (Verilator lacks UVM).
// =============================================================================
`ifndef _SVA_BASIC_RAL_PKG_SV
`define _SVA_BASIC_RAL_PKG_SV

package sva_basic_ral_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"


  // ---- register `status` --------------------------------------
  class sva_basic_status_reg extends uvm_reg;

    rand uvm_reg_field error;

    rand uvm_reg_field warn;


    function new(string name = "sva_basic_status_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.error = uvm_reg_field::type_id::create("error");
      this.error.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (0),
        .access                  ("W1C"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.warn = uvm_reg_field::type_id::create("warn");
      this.warn.configure(
        .parent                  (this),
        .size                    (1),
        .lsb_pos                 (1),
        .access                  ("W1C"),
        .volatile                (1'b0),
        .reset                   (1'h0),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : sva_basic_status_reg


  // ---- register `version` --------------------------------------
  class sva_basic_version_reg extends uvm_reg;

    rand uvm_reg_field major;

    rand uvm_reg_field minor;

    rand uvm_reg_field patch;


    function new(string name = "sva_basic_version_reg");
      super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();

      this.major = uvm_reg_field::type_id::create("major");
      this.major.configure(
        .parent                  (this),
        .size                    (8),
        .lsb_pos                 (24),
        .access                  ("RO"),
        .volatile                (1'b0),
        .reset                   (8'hca),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.minor = uvm_reg_field::type_id::create("minor");
      this.minor.configure(
        .parent                  (this),
        .size                    (8),
        .lsb_pos                 (16),
        .access                  ("RO"),
        .volatile                (1'b0),
        .reset                   (8'hfe),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

      this.patch = uvm_reg_field::type_id::create("patch");
      this.patch.configure(
        .parent                  (this),
        .size                    (16),
        .lsb_pos                 (0),
        .access                  ("RO"),
        .volatile                (1'b0),
        .reset                   (16'hbabe),
        .has_reset               (1'b1),
        .is_rand                 (1'b1),
        .individually_accessible (1'b0));

    endfunction

  endclass : sva_basic_version_reg



  // ---- register block -------------------------------------------------------
  class sva_basic_reg_block extends uvm_reg_block;

    rand sva_basic_status_reg status;

    rand sva_basic_version_reg version;


    function new(string name = "sva_basic_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      // Byte-aligned LITTLE_ENDIAN map at base 0; bus width derives from
      // the regblock's CPUIF data width.
      this.default_map = create_map(
        .name      ("default_map"),
        .base_addr (8'h0),
        .n_bytes   (4),
        .endian    (UVM_LITTLE_ENDIAN),
        .byte_addressing (1'b1));


      this.status = sva_basic_status_reg::type_id::create("status");
      this.status.configure(this, null, "");
      this.status.build();
      this.default_map.add_reg(this.status, 8'h0, "RW");



      this.version = sva_basic_version_reg::type_id::create("version");
      this.version.configure(this, null, "");
      this.version.build();
      this.default_map.add_reg(this.version, 8'h4, "RO");



      lock_model();
    endfunction

  endclass : sva_basic_reg_block

endpackage : sva_basic_ral_pkg

`endif // _SVA_BASIC_RAL_PKG_SV

// =============================================================================
// UVM RAL smoke sequence for `sva_basic_ral_pkg`.
//
// A minimal `uvm_sequence` that exercises every register in the model
// with a read-after-write (RAW) pattern. Intended as a starting point for
// verification teams — not run by OSS CI (Verilator lacks UVM). Drop the
// sequence onto a sequencer connected to a `uvm_reg_predictor` and the
// generated `sva_basic_reg_block` to get smoke
// coverage of the RAL model itself.
// =============================================================================
`ifndef _SVA_BASIC_RAL_SMOKE_SEQ_SV
`define _SVA_BASIC_RAL_SMOKE_SEQ_SV

package sva_basic_ral_smoke_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import sva_basic_ral_pkg::*;

  class sva_basic_ral_smoke_seq extends uvm_sequence;
    `uvm_object_utils(sva_basic_ral_smoke_seq)

    sva_basic_reg_block model;
    uvm_status_e status;
    uvm_reg_data_t rdata;
    uvm_reg_data_t wdata;

    function new(string name = "sva_basic_ral_smoke_seq");
      super.new(name);
    endfunction

    virtual task body();
      if (model == null) begin
        `uvm_fatal(get_type_name(), "RAL model handle not assigned before smoke seq")
      end


      // status — RW: write pattern, read back, check equality.
      wdata = 'h5aa55aa5;
      model.status.write(status, wdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("write(status) status=%s", status.name()))
      end
      model.status.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(status) status=%s", status.name()))
      end



      // version — RO: read-only smoke (no write).
      model.version.read(status, rdata);
      if (status != UVM_IS_OK) begin
        `uvm_error(get_type_name(),
                   $sformatf("read(version) status=%s", status.name()))
      end


    endtask

  endclass : sva_basic_ral_smoke_seq

endpackage : sva_basic_ral_smoke_pkg

`endif // _SVA_BASIC_RAL_SMOKE_SEQ_SV

